### ISSUE TITLE
Why The app doesn't work properly in the background for a long time. It stops working in about 15 seconds , in internal_plugin_service project ?

### ISSUE THREAD

**Issue by willbetheone** [Dev-hwang/flutter_foreground_task_example#3] opened 2024-11-19 02:11 UTC
Hi 
Why The app doesn't work properly in the background for a long time. It stops working in about 15 seconds , in internal_plugin_service project ? 

Look forward to your reply

-- alpha

**Comment by Dev-hwang** [comment] 2024-11-21 03:21
Duplicate of [#294](https://github.com/Dev-hwang/flutter_foreground_task/issues/294)

**Closed as completed by Dev-hwang** 2024-11-21 03:21 UTC
